FORMAT: 1A

# Backgammon gameserver 


## Match [/match]

### Start a new match [POST]

+ Request (application/json)
    + Attributes (New Match)
    

+ Response 200 (application/json)
    + Attributes (Match Response)
    

### Update match [PUT]

+ Request (application/json)
    + Attributes (Update Match)

+ Response 200 (application/json)
    + Attributes (Match Response)

## Game [/game]

### Start a new game [POST]

+ Request (application/json)
    + Attributes (New Game)
    

+ Response 200 (application/json)
    + Attributes (Game Response)
    

### Update game [PUT]

+ Request (application/json)
    + Attributes (Update Game)

+ Response 200 (application/json)
    + Attributes (Game Response)

## Move [/move]

### Start a new move [POST]

+ Request (application/json)
    + Attributes (New Move)
    

+ Response 200 (application/json)
    + Attributes (Move Response)
    

### Update move [PUT]

+ Request (application/json)
    + Attributes (Update Move)

+ Response 200 (application/json)
    + Attributes (Move Response)

# Data Structures

## New Match (object)
+ player_0: Mock player 0 (string, required) - Name of player 0 

## Update Match (object)
+ id: dc52008418134ccd9ad65622bc18a524 (string, required) - Id of the match
+ Include Match Base

## Match Response (object)
+ id: dc52008418134ccd9ad65622bc18a524 (string) - Id of the match
+ Include Match Base

## Match Base (object)
+ player_0: Mock player 0 (string) - Name of player 0 
+ games (array[Game Response]) - Related games

## New Game (object)
+ match_id: dc52008418134ccd9ad65622bc18a524 (string, required) - Id of the match

## Update Game (object)
+ id: 87d610d7f60e08939c105788a17facbf (string, required) - Id of the game
+ Include Game Base

## Game Response (object)
+ id: 87d610d7f60e08939c105788a17facbf (string) - Id of the game
+ Include Game Base

## Game Base (object)
+ match_id: dc52008418134ccd9ad65622bc18a524 (string) - Id of the match
+ moves (array[Move Response]) - Related moved

## New Move (object)
+ game_id: 87d610d7f60e08939c105788a17facbf (string, required) - Id of the game

## Update Move (object)
+ id: 0505c163a95d34cbe74626affccfa425 (string, required) - Id of the move
+ Include Move Base

## Move Response (object)
+ id: 0505c163a95d34cbe74626affccfa425 (string) - Id of the move
+ Include Move Base

## Move Base (object)
+ game_id: 87d610d7f60e08939c105788a17facbf (string) - Id of the game